import hre from "hardhat";

import { installResilientDns } from "./net";
installResilientDns();

import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

const { ethers } = hre;

/**
 * Freeze the leaf to owner map into the frontend bundle.
 *
 *     npx hardhat run scripts/snapshot-leaves.ts --network sepolia
 *
 * WHY THIS EXISTS. The register screen discovered leaf owners by scanning
 * `LeafAssigned` logs, and that scan is the single least reliable read in the
 * app: a free RPC tier serves it inconsistently, so the same windows that
 * return 24 events from a node script come back empty in a browser. The result
 * was a register showing 32 empty slots under a header reading "24 / 32", on
 * the app's main route, on roughly two loads in three.
 *
 * A leaf is assigned once and never reassigned, so the mapping is immutable
 * and a build-time snapshot of it is not a cache that can go stale in the
 * usual sense. It can only ever be INCOMPLETE, when someone commits after the
 * snapshot was taken, and the frontend still runs the log scan to pick those
 * up. The difference is that a failed scan now costs the newest depositors
 * rather than the entire register.
 *
 * Balances are NOT snapshotted. Those change on every commit and release, and
 * they are read at runtime by one multicall, which is the reliable half.
 *
 * Re-run this after seeding, and commit the result.
 */

const OUT = join(__dirname, "..", "web", "src", "lib", "leaves.json");

async function main() {
  const network = hre.network.name;
  const rec = JSON.parse(readFileSync(join(__dirname, "..", "deployments", `${network}.json`), "utf8"));

  const provider = ethers.provider;
  const head = await provider.getBlockNumber();
  const from = Number(process.env.DEPLOY_BLOCK ?? "11578000");
  const topic = ethers.id("LeafAssigned(address,uint256)");

  const owners = new Map<number, string>();
  let failed = 0;
  for (let start = from; start <= head; start += 9_000) {
    const end = Math.min(start + 9_000, head);
    let got = false;
    // Three attempts per window. A window silently dropped here would be
    // baked into the bundle, which is worse than the bug this replaces.
    for (let i = 0; i < 3 && !got; i++) {
      try {
        const logs = await provider.getLogs({
          address: rec.pool,
          topics: [topic],
          fromBlock: start,
          toBlock: end,
        });
        for (const l of logs) {
          owners.set(Number(BigInt(l.topics[2])), ethers.getAddress("0x" + l.topics[1].slice(26)));
        }
        got = true;
      } catch {
        await new Promise((r) => setTimeout(r, 2_000 * (i + 1)));
      }
    }
    if (!got) failed++;
  }

  if (failed > 0) {
    throw new Error(
      `${failed} log windows could not be read after three attempts each. ` +
        `Refusing to write an incomplete snapshot: an empty register is a visible bug, ` +
        `a half-full one is a silent one.`,
    );
  }

  const pool = await ethers.getContractAt("SortisPool", rec.pool);
  const onChainCount = Number(await pool.leafCount());
  if (owners.size !== onChainCount) {
    throw new Error(
      `found ${owners.size} LeafAssigned events but leafCount() reports ${onChainCount}. ` +
        `Not writing a snapshot that disagrees with the contract.`,
    );
  }

  const sorted = [...owners.entries()].sort((a, b) => a[0] - b[0]);
  writeFileSync(
    OUT,
    JSON.stringify(
      {
        note: "Generated by scripts/snapshot-leaves.ts. Leaf assignment is permanent, so this is a snapshot rather than a cache. Re-run after seeding.",
        network,
        pool: rec.pool,
        takenAtBlock: head,
        takenAt: new Date().toISOString(),
        leaves: Object.fromEntries(sorted),
      },
      null,
      2,
    ) + "\n",
  );

  console.log(`wrote ${sorted.length} leaves to web/src/lib/leaves.json at block ${head}`);
  for (const [leaf, owner] of sorted.slice(0, 3)) console.log(`  ${leaf}  ${owner}`);
  console.log(`  ...`);
}

main().catch((error) => {
  console.error("SNAPSHOT FAILED:", error?.message ?? error);
  process.exitCode = 1;
});
